spring.application.name=demo
# for https
server.forward-headers-strategy=framework 
spring.datasource.url=jdbc:mysql://localhost::3306/carelink?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update